language: python
python:
  - "2.7"
  - "3.3"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install -r test_requirements.txt --use-mirrors"
  - "pip install -r test_requirements26.txt --use-mirrors || exit"
  - "pip install pydes --use-mirrors"
script: nosetests
